name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    environment: test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/phpunit
